import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/header';
import Footer from './components/footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const RootLayout = ({ children }) => {
  return (
    <>
      <Header />
      <div className={inter.className}>{children}</div>
      <Footer />
    </>
  );
};

export default RootLayout;